import type {
  DashboardPayload,
  GraphLink,
  GraphNode,
  TribeResult,
} from "./types";

export const mockTribeResult: TribeResult = {
  enabled: true,
  response_strength: 0.72,
  response_variance: 0.18,
  response_spread: 0.45,
  scored_text:
    "Personas showed strong reactions. The panel largely agrees on overall appeal. Some features still split the room.",
};

export const mockDashboardPayload: DashboardPayload = {
  project_id: "mock-project-id",
  scenario_id: "scenario-iphone-18",
  consensus_score: 0.61,
  disagreement_score: 0.34,
  evidence_coverage: 0.89,
  top_risks: [
    { label: "Premium price stretch", score: 0.79 },
    { label: "Privacy trust skepticism", score: 0.66 },
    { label: "Incremental redesign fatigue", score: 0.52 },
  ],
  top_wins: [
    { label: "Camera leap feels visible", score: 0.86 },
    { label: "Battery confidence story", score: 0.81 },
    { label: "Tight ecosystem handoff", score: 0.74 },
  ],
  feature_scores: {
    camera: {
      mean: 0.82,
      min: 0.69,
      max: 0.95,
      std: 0.09,
      persona_scores: { p1: 0.95, p2: 0.78, p3: 0.69, p4: 0.88, p5: 0.8 },
    },
    battery: {
      mean: 0.76,
      min: 0.62,
      max: 0.88,
      std: 0.08,
      persona_scores: { p1: 0.84, p2: 0.81, p3: 0.74, p4: 0.88, p5: 0.62 },
    },
    price: {
      mean: 0.44,
      min: 0.18,
      max: 0.73,
      std: 0.2,
      persona_scores: { p1: 0.42, p2: 0.39, p3: 0.18, p4: 0.48, p5: 0.73 },
    },
    design: {
      mean: 0.68,
      min: 0.51,
      max: 0.86,
      std: 0.11,
      persona_scores: { p1: 0.86, p2: 0.61, p3: 0.51, p4: 0.71, p5: 0.71 },
    },
    privacy: {
      mean: 0.56,
      min: 0.3,
      max: 0.91,
      std: 0.24,
      persona_scores: { p1: 0.47, p2: 0.91, p3: 0.41, p4: 0.69, p5: 0.3 },
    },
    ecosystem: {
      mean: 0.73,
      min: 0.36,
      max: 0.95,
      std: 0.21,
      persona_scores: { p1: 0.76, p2: 0.58, p3: 0.36, p4: 0.95, p5: 0.68 },
    },
  },
  personas: [
    {
      persona_id: "p1",
      segment_label: "Early Adopter Enthusiast",
      summary:
        "Tracks every launch keynote and upgrades for visible technical jumps. Loves features that feel brag-worthy within the first week.",
      adoption_likelihood: 82,
      strongest_positive: "Computational photography feels instantly impressive.",
      strongest_concern: "Launch messaging could oversell AI without clear daily value.",
      feature_priorities: {
        camera: 0.99,
        battery: 0.84,
        design: 0.86,
        ecosystem: 0.76,
        privacy: 0.47,
        price: 0.42,
      },
    },
    {
      persona_id: "p2",
      segment_label: "Privacy-Conscious Professional",
      summary:
        "Needs a phone that blends premium polish with trustworthy data handling. Evaluates claims through a risk-management lens.",
      adoption_likelihood: 58,
      strongest_positive: "Battery gains reduce friction during heavy travel days.",
      strongest_concern: "Any ambiguous AI processing language will trigger trust concerns.",
      feature_priorities: {
        privacy: 0.98,
        battery: 0.81,
        camera: 0.78,
        ecosystem: 0.58,
        design: 0.61,
        price: 0.39,
      },
    },
    {
      persona_id: "p3",
      segment_label: "Budget-Minded Student",
      summary:
        "Wants flagship-level social proof but compares every spec against total cost. A good story is not enough if trade-in math still hurts.",
      adoption_likelihood: 45,
      strongest_positive: "Battery and camera are finally strong enough to feel future-proof.",
      strongest_concern: "Price ladder still feels disconnected from student reality.",
      feature_priorities: {
        price: 0.97,
        battery: 0.74,
        camera: 0.69,
        design: 0.51,
        privacy: 0.41,
        ecosystem: 0.36,
      },
    },
    {
      persona_id: "p4",
      segment_label: "Ecosystem Loyalist",
      summary:
        "Already lives inside the brand's device stack and values frictionless continuity. Measures delight by how invisible the ecosystem becomes.",
      adoption_likelihood: 71,
      strongest_positive: "Cross-device continuity makes the phone feel like the control hub.",
      strongest_concern: "Design changes seem too subtle to signal a generational leap.",
      feature_priorities: {
        ecosystem: 0.95,
        battery: 0.88,
        camera: 0.88,
        design: 0.71,
        privacy: 0.69,
        price: 0.48,
      },
    },
    {
      persona_id: "p5",
      segment_label: "Skeptical Tech Journalist",
      summary:
        "Interrogates every claim against broader category trends and competitive context. Responds well to evidence, badly to hype.",
      adoption_likelihood: 33,
      strongest_positive: "Camera improvements are credible because they show up in side-by-side examples.",
      strongest_concern: "The value proposition still feels too incremental for the price jump.",
      feature_priorities: {
        price: 0.73,
        privacy: 0.3,
        battery: 0.62,
        camera: 0.8,
        design: 0.71,
        ecosystem: 0.68,
      },
    },
  ],
  quotes: [
    {
      persona_id: "p1",
      segment_label: "Early Adopter Enthusiast",
      quote: "If the camera demo looks half as good in real life, I will show this off the same day I buy it.",
      facet: "camera",
      sentiment: "positive",
    },
    {
      persona_id: "p2",
      segment_label: "Privacy-Conscious Professional",
      quote: "I need one sentence that tells me exactly where the AI processing happens. Anything vague hurts trust.",
      facet: "privacy",
      sentiment: "negative",
    },
    {
      persona_id: "p3",
      segment_label: "Budget-Minded Student",
      quote: "This sounds great until the monthly payment shows up. Then it becomes another maybe-later purchase.",
      facet: "price",
      sentiment: "negative",
    },
    {
      persona_id: "p4",
      segment_label: "Ecosystem Loyalist",
      quote: "The hardware matters, but the reason I stay is how naturally it fits with the rest of my devices.",
      facet: "ecosystem",
      sentiment: "positive",
    },
    {
      persona_id: "p5",
      segment_label: "Skeptical Tech Journalist",
      quote: "I believe the camera claims more than the AI claims because the camera evidence is tangible.",
      facet: "camera",
      sentiment: "neutral",
    },
    {
      persona_id: "p2",
      segment_label: "Privacy-Conscious Professional",
      quote: "Battery improvement is one of the few promises that can justify a mid-cycle upgrade for me.",
      facet: "battery",
      sentiment: "positive",
    },
    {
      persona_id: "p3",
      segment_label: "Budget-Minded Student",
      quote: "If trade-in credits soften the price, I could talk myself into it. Without that, no chance.",
      facet: "price",
      sentiment: "neutral",
    },
    {
      persona_id: "p1",
      segment_label: "Early Adopter Enthusiast",
      quote: "The design feels elegant, but I am still waiting for a truly surprising visual cue that screams new generation.",
      facet: "design",
      sentiment: "neutral",
    },
    {
      persona_id: "p4",
      segment_label: "Ecosystem Loyalist",
      quote: "The best part is not one killer feature, it is how the whole stack feels calmer and faster together.",
      facet: "ecosystem",
      sentiment: "positive",
    },
    {
      persona_id: "p5",
      segment_label: "Skeptical Tech Journalist",
      quote: "The narrative is competent, but the burden is on the company to prove this is more than incremental polish.",
      facet: "design",
      sentiment: "negative",
    },
  ],
  round1_responses: [
    {
      persona_id: "p1",
      overall_reaction: "Excited by the camera and overall flagship feel.",
      adoption_likelihood_0_100: 78,
      strongest_positive: "Camera improvements feel real.",
      strongest_concern: "AI story may be fuzzy.",
      feature_scores: { camera: 0.95, battery: 0.81, price: 0.4, design: 0.84, privacy: 0.46, ecosystem: 0.74 },
      cited_chunk_ids: ["chunk_01", "chunk_07"],
    },
    {
      persona_id: "p2",
      overall_reaction: "Interested but waiting for privacy clarity.",
      adoption_likelihood_0_100: 55,
      strongest_positive: "Battery life.",
      strongest_concern: "Data handling transparency.",
      feature_scores: { camera: 0.74, battery: 0.79, price: 0.38, design: 0.59, privacy: 0.89, ecosystem: 0.55 },
      cited_chunk_ids: ["chunk_03", "chunk_08"],
    },
    {
      persona_id: "p3",
      overall_reaction: "Features land well, but price anchors the decision downward.",
      adoption_likelihood_0_100: 41,
      strongest_positive: "Battery value.",
      strongest_concern: "Affordability.",
      feature_scores: { camera: 0.66, battery: 0.72, price: 0.16, design: 0.49, privacy: 0.42, ecosystem: 0.34 },
      cited_chunk_ids: ["chunk_04", "chunk_09"],
    },
    {
      persona_id: "p4",
      overall_reaction: "Positive because the ecosystem payoff compounds.",
      adoption_likelihood_0_100: 69,
      strongest_positive: "Ecosystem continuity.",
      strongest_concern: "Design novelty.",
      feature_scores: { camera: 0.85, battery: 0.86, price: 0.45, design: 0.68, privacy: 0.68, ecosystem: 0.95 },
      cited_chunk_ids: ["chunk_02", "chunk_10"],
    },
    {
      persona_id: "p5",
      overall_reaction: "Respectful but unconvinced this changes the category math.",
      adoption_likelihood_0_100: 36,
      strongest_positive: "Credible camera step.",
      strongest_concern: "Thin value delta.",
      feature_scores: { camera: 0.78, battery: 0.61, price: 0.71, design: 0.69, privacy: 0.32, ecosystem: 0.66 },
      cited_chunk_ids: ["chunk_05", "chunk_11"],
    },
  ],
  round2_responses: [
    {
      persona_id: "p1",
      overall_reaction: "Peer discussion made the battery story feel more complete, raising interest.",
      adoption_likelihood_0_100: 82,
      strongest_positive: "Camera plus battery combination.",
      strongest_concern: "Messaging still risks sounding generic on AI.",
      feature_scores: { camera: 0.95, battery: 0.84, price: 0.42, design: 0.86, privacy: 0.47, ecosystem: 0.76 },
      cited_chunk_ids: ["chunk_01", "chunk_06", "chunk_07"],
    },
    {
      persona_id: "p2",
      overall_reaction: "Debate reinforced privacy caution but did not erase functional appeal.",
      adoption_likelihood_0_100: 58,
      strongest_positive: "Battery confidence.",
      strongest_concern: "Privacy trust still unanswered.",
      feature_scores: { camera: 0.78, battery: 0.81, price: 0.39, design: 0.61, privacy: 0.91, ecosystem: 0.58 },
      cited_chunk_ids: ["chunk_03", "chunk_08", "chunk_12"],
    },
    {
      persona_id: "p3",
      overall_reaction: "The camera story improved the emotional pull, but price remains the blocker.",
      adoption_likelihood_0_100: 45,
      strongest_positive: "Camera feels future-proof.",
      strongest_concern: "Price-to-value gap.",
      feature_scores: { camera: 0.69, battery: 0.74, price: 0.18, design: 0.51, privacy: 0.41, ecosystem: 0.36 },
      cited_chunk_ids: ["chunk_04", "chunk_09", "chunk_12"],
    },
    {
      persona_id: "p4",
      overall_reaction: "Deliberation increased confidence that continuity benefits justify the upgrade.",
      adoption_likelihood_0_100: 71,
      strongest_positive: "Ecosystem handoff quality.",
      strongest_concern: "Not visually dramatic enough.",
      feature_scores: { camera: 0.88, battery: 0.88, price: 0.48, design: 0.71, privacy: 0.69, ecosystem: 0.95 },
      cited_chunk_ids: ["chunk_02", "chunk_10", "chunk_12"],
    },
    {
      persona_id: "p5",
      overall_reaction: "Group conversation hardened skepticism on price discipline.",
      adoption_likelihood_0_100: 33,
      strongest_positive: "Camera evidence remains strong.",
      strongest_concern: "Premium premium pricing for incremental utility.",
      feature_scores: { camera: 0.8, battery: 0.62, price: 0.73, design: 0.71, privacy: 0.3, ecosystem: 0.68 },
      cited_chunk_ids: ["chunk_05", "chunk_11", "chunk_12"],
    },
  ],
  moderator_question:
    "Which improvement feels most likely to justify upgrading within six months: camera reliability, battery confidence, or ecosystem continuity?",
  analyst_summary: {
    consensus_themes: [
      "Camera gains feel credible and immediately legible.",
      "Battery life is the safest cross-segment selling point.",
    ],
    disagreement_themes: [
      "Price sensitivity splits aspirational and skeptical segments.",
      "Privacy messaging creates confidence for some and friction for others.",
    ],
    top_risks: [
      "Over-claiming on AI",
      "Weak affordability narrative",
    ],
    top_wins: [
      "Camera proof points",
      "Battery clarity",
    ],
    feature_recommendations: [
      "Lead with camera evidence before abstract AI promises.",
      "Bundle trade-in messaging with student and family use cases.",
    ],
    messaging_suggestions: [
      "Translate privacy claims into plain-language assurances.",
      "Show ecosystem continuity through everyday moments, not feature lists.",
    ],
    evidence_gaps: [
      "No clear proof that AI features save time for skeptical professionals.",
    ],
  },
  tribe: mockTribeResult,
};

export const mockGraphNodes: GraphNode[] = [
  { id: "product", label: "iPhone 18", type: "Product", description: "Core concept under review." },
  { id: "camera", label: "Camera leap", type: "Feature", description: "High-confidence feature driver." },
  { id: "battery", label: "Battery confidence", type: "Feature", description: "Stable cross-persona positive." },
  { id: "price", label: "Premium pricing", type: "Concern", description: "Primary disagreement node." },
  { id: "privacy", label: "Privacy trust", type: "Concern", description: "Trust lens for professionals." },
  { id: "loyalists", label: "Ecosystem loyalists", type: "Segment", description: "High ecosystem affinity cluster." },
];

export const mockGraphLinks: GraphLink[] = [
  { source: "product", target: "camera", label: "strengthens" },
  { source: "product", target: "battery", label: "improves" },
  { source: "product", target: "price", label: "pressures" },
  { source: "product", target: "privacy", label: "raises" },
  { source: "loyalists", target: "product", label: "champions" },
  { source: "price", target: "camera", label: "undercuts" },
];
